<?php
if (empty($isAdmin)) { http_response_code(404); exit; }
$orderLabels = ['awaiting' => 'En attente', 'expired' => 'Délai expiré', 'review' => 'À vérifier', 'paid' => 'Paiement validé', 'delivered' => 'Livrée', 'cancelled' => 'Annulée'];
$orderList = [];
try { $orderList = array_reverse(orders_store(), true); } catch (Throwable $exception) { echo '<p role="alert">Impossible de lire les commandes.</p>'; }
$search = is_string($_GET['search'] ?? null) ? trim($_GET['search']) : '';
if ($search !== '') $orderList = array_filter($orderList, function ($order) use ($search) { return stripos($order['id'] . ' ' . $order['email'] . ' ' . $order['txid'], $search) !== false; });
?>
<section class="orders-admin"><div class="panel order-admin-card"><h1>Commandes</h1><p>Vérifiez la réception dans votre portefeuille : réseau, destination, montant, confirmations et absence de paiement déjà utilisé. Un TXID déclaré ne suffit pas.</p><p>La livraison et les e-mails restent manuels. Le message client ci-dessous apparaît sur le lien privé de suivi.</p><form method="get"><input type="hidden" name="tab" value="orders"><label for="order-search">Rechercher un numéro, un e-mail ou un TXID</label><input id="order-search" name="search" value="<?= h($search) ?>"><button class="button">Rechercher</button></form></div>
<?php if (!$orderList): ?><p class="panel order-admin-card">Aucune commande à afficher.</p><?php endif; ?>
<?php foreach ($orderList as $order): ?>
<details class="panel order-admin-card"><summary><?= h($order['id']) ?> · <?= h($order['product_name']) ?> · <?= h($order['total_usd']) ?> USD · <?= h($orderLabels[order_status($order)]) ?><?= $order['mode'] === 'demo' ? ' · DÉMO' : '' ?></summary>
<dl><?php foreach (['email' => 'E-mail', 'qty' => 'Quantité', 'network' => 'Réseau', 'address' => 'Destination', 'amount' => 'Montant crypto', 'txid' => 'TXID déclaré', 'customer_note' => 'Message du client'] as $key => $label): ?><dt><?= h($label) ?></dt><dd><?= nl2br(h($order[$key])) ?><?= $key === 'amount' ? ' ' . h($order['asset']) : '' ?></dd><?php endforeach; ?><dt>Création / échéance UTC</dt><dd><?= h(gmdate('Y-m-d H:i', $order['created_at'])) ?> / <?= h(gmdate('Y-m-d H:i', $order['expires_at'])) ?></dd></dl>
<form method="post" action="admin.php?tab=orders"><input type="hidden" name="csrf_token" value="<?= h($_SESSION['csrf_token']) ?>"><input type="hidden" name="save_order" value="1"><input type="hidden" name="order_id" value="<?= h($order['id']) ?>"><label>Statut<select name="order_status"><?php foreach ($orderLabels as $key => $label): if ($key === 'expired') continue; ?><option value="<?= h($key) ?>" <?= $key === $order['status'] ? 'selected' : '' ?>><?= h($label) ?></option><?php endforeach; ?></select></label><label>Message visible par le client<textarea name="public_note" maxlength="1000" rows="3"><?= h($order['public_note']) ?></textarea></label><label><input type="checkbox" name="verified" value="1"> J'ai vérifié le paiement dans le portefeuille, ou effectué la livraison correspondant au nouveau statut.</label><button class="button primary">Enregistrer la commande</button></form>
<h3>Historique (UTC)</h3><ul><?php foreach ($order['history'] as $event): ?><li><?= h(gmdate('Y-m-d H:i', $event['at'])) ?> · <?= h($orderLabels[$event['status']]) ?> · <?= h($event['actor']) ?><?= isset($event['txid']) ? ' · ' . h($event['txid']) : '' ?></li><?php endforeach; ?></ul>
</details><?php endforeach; ?></section>
